### ISSUE TITLE
Error deleting mozprofile

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#100]
I see this at the end of run:

```
* ** Test session firefox complete **
*  Terminating process.
*  Exception ignored in: <function BaseProfile.__del__ at 0x11040f8c8>
*  Traceback (most recent call last):
*   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/mozprofile/profile.py", line 76, in __del__
*   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/mozprofile/profile.py", line 258, in cleanup
*   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/mozprofile/profile.py", line 272, in clean_preferences
*   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/mozprofile/profile.py", line 321, in pop_preferences
*  NameError: name 'open' is not defined
```

**Comment by mwobensmith** [comment]
This may be a non-issue, as output above indicates use of python 3.7, while we currently only can support 3.5.

**Comment by silviuFlorin** [comment]
This issue is not reproducible on Python 3.5.3

**Comment by mwobensmith** [comment]
Bad Python environment, closing issue.
