### ISSUE TITLE
Run log json is not created on session finish

### ISSUE THREAD

**Issue by mariusandreifilip** [mozilla/iris2#256]
Traceback (most recent call last):
  File "C:\Users\andrei.filip\.virtualenvs\iris2-ICp0-HFB\Scripts\iris-script.py", line 11, in <module>
    load_entry_point('iris2', 'console_scripts', 'iris')()
  File "c:\iris2\src\__main__.py", line 83, in main
    pytest.main(pytest_args, plugins=[target_plugin])
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\_pytest\config\__init__.py", line 79, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\_pytest\main.py", line 242, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\_pytest\main.py", line 235, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\iris2\targets\firefox\app.py", line 100, in pytest_sessionfinish
    BaseTarget.pytest_sessionfinish(self, session)
  File "c:\iris2\src\base\target.py", line 94, in pytest_sessionfinish
    create_run_log(self)
  File "c:\iris2\src\core\util\json_utils.py", line 141, in create_run_log
    tests = {'all_tests': convert_test_list(app.completed_tests),
  File "c:\iris2\src\core\util\json_utils.py", line 189, in convert_test_list
    'code': get_failing_code(test.node_name, int(test.line))
  File "c:\iris2\src\core\util\json_utils.py", line 223, in get_failing_code
    f = open(file, 'r').readlines()
  File "c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2259: character maps to <undefined>

**Comment by mariusandreifilip** [comment]
The error occurs when a file needs to be opened  :
def get_failing_code(file, line):
    f = open(file, 'r').readlines()

Fixed in branch issue_256
