### ISSUE TITLE
Errors with mozdownload

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris2#69]
New in today's code:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/_pytest/main.py", line 207, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/mwobensmith/PycharmProjects/iris2/targets/firefox/app.py", line 55, in pytest_sessionstart
INTERNALERROR>     FX_Collection.add(args.firefox, args.locale)
INTERNALERROR>   File "/Users/mwobensmith/PycharmProjects/iris2/targets/firefox/firefox_app/fx_collection.py", line 10, in add
INTERNALERROR>     self.fx_collection[fx_browser_key] = FirefoxApp(version=version, locale=locale)
INTERNALERROR>   File "/Users/mwobensmith/PycharmProjects/iris2/targets/firefox/firefox_app/fx_browser.py", line 191, in __init__
INTERNALERROR>     path = get_test_candidate(version, locale)
INTERNALERROR>   File "/Users/mwobensmith/PycharmProjects/iris2/targets/firefox/firefox_app/fx_browser.py", line 274, in get_test_candidate
INTERNALERROR>     firefox_dmg = scraper.download()
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/mozdownload/scraper.py", line 320, in download
INTERNALERROR>     errors.TimeoutError))
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/mozdownload/scraper.py", line 143, in _retry
INTERNALERROR>     return redo.retry(func, **retry_kwargs)
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/redo/__init__.py", line 165, in retry
INTERNALERROR>     return action(*args, **kwargs)
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/mozdownload/scraper.py", line 296, in _download
INTERNALERROR>     maxval=max_value).start()
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/progressbar/bar.py", line 656, in start
INTERNALERROR>     self.update(self.min_value, force=True)
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/progressbar/bar.py", line 589, in update
INTERNALERROR>     StdRedirectMixin.update(self, value=value)
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/progressbar/bar.py", line 144, in update
INTERNALERROR>     self.fd.write('\r' + ' ' * self.term_width + '\r')
INTERNALERROR>   File "/Users/mwobensmith/.local/share/virtualenvs/iris2-Fh8pD0FE/lib/python3.7/site-packages/_pytest/capture.py", line 420, in write
INTERNALERROR>     self.buffer.write(obj)
INTERNALERROR> ValueError: I/O operation on closed file
```

**Comment by silviuFlorin** [comment]
@mwobensmith I investigated this issue. The problem is in scan_all_tests() from create_target_json()

**Comment by mwobensmith** [comment]
Fixed
